# Generated by Django 4.2.16 on 2024-10-01 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_contextbuttontype'),
        ('users', '0005_alter_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContextButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка')),
                ('button_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buttons', to='common.contextbuttontype', verbose_name='Тип кнопки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_buttons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Контекстная кнопка пользователей',
                'verbose_name_plural': 'Контекстные кнопки пользователей',
                'unique_together': {('user', 'button_type')},
            },
        ),
    ]
