# Generated by Django 4.2.16 on 2024-11-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usercontextbutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание профиля'),
        ),
    ]
