# Generated by Django 4.2.16 on 2024-09-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='is_passed_moderation',
            field=models.BooleanField(default=False, verbose_name='Прошло модерацию'),
        ),
    ]
