# Generated by Django 4.2.16 on 2024-09-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_itemdata_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdatacollection',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemdatastatus',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
