# Generated by Django 4.2.16 on 2024-10-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_itemdatacollection_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextButtonType',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('verbose', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Тип контекстной кнопки',
                'verbose_name_plural': 'Типы контекстных кнопок',
                'ordering': ('verbose',),
            },
        ),
    ]
