# Generated by Django 4.2.16 on 2024-11-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_itemdatacontextbutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='images/previews/', verbose_name='Превью'),
        ),
    ]
