# Generated by Django 4.2.16 on 2024-11-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_itemdata_image_alter_itemdata_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextbuttontype',
            name='host_regex',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
