# Generated by Django 4.2.16 on 2024-11-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_contextbuttontype_host_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='short_description',
            field=models.TextField(default='', max_length=256, verbose_name='Краткое описание'),
        ),
    ]
